// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0bmWGm2iwTgGLfMSA7JxaD-8-n0Hz-y4',
    appId: '1:1068546138732:web:8d4b172aa1b0f2b95b6e49',
    messagingSenderId: '1068546138732',
    projectId: 'shoes-business-6c6ec',
    authDomain: 'shoes-business-6c6ec.firebaseapp.com',
    storageBucket: 'shoes-business-6c6ec.firebasestorage.app',
    measurementId: 'G-GPMWERXLSW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzJ3wpg2u2em341EHdB8r5FlWoy0DfXas',
    appId: '1:1068546138732:android:a6f28ff05bf4ec3a5b6e49',
    messagingSenderId: '1068546138732',
    projectId: 'shoes-business-6c6ec',
    storageBucket: 'shoes-business-6c6ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM23xbhoqUSLDzUrNdNUrKl-gSTos6ejY',
    appId: '1:1068546138732:ios:e9b93a4a30e8ce505b6e49',
    messagingSenderId: '1068546138732',
    projectId: 'shoes-business-6c6ec',
    storageBucket: 'shoes-business-6c6ec.firebasestorage.app',
    iosBundleId: 'com.example.shoesBusiness',
  );
}
